export const RouteEnum = {
  SIGNIN: "/signin",
  SIGNUP: "/signup",
  SIGNUP_RESEND_CREDETIAL: "/signup/resend-credential",
  SIGNUP_VERIFICATION: "/signup/verification",
  FORGOT_PASSWORD: "/forgot-password",
  FORGOT_PASSWORD_RESET: "/forgot-password/reset",
  HOME: "/",
  SOLUTIONS: "/solutions",
  ABOUT: "/about",
  CONTACT: "/contact",
  DASHBOARD: "/",
  TRANSACTIONS: "/transactions",
  CONTACT_US: "/contact-us",
  CONTACT_US_SUPPORT: "/contact-us/support",
  CONTACT_US_FAQS: "/contact-us/faqs",
  PROFILE: "/profile",
  SETTINGS: "/settings",
};
