export const RouteEnum = {
  SIGNIN: "/signin",
  SIGNUP: "/signup",
  SIGNUP_RESEND_CREDETIAL: "/signup/resend-credential",
  SIGNUP_VERIFICATION: "/signup/verification",
  FORGOT_PASSWORD: "/forgot-password",
  FORGOT_PASSWORD_RESET: "/forgot-password/reset",
  HOME: "/",
  SOLUTIONS: "/solutions",
  ABOUT: "/about",
  CONTACT: "/contact",
  DASHBOARD: "/",
  TRANSACTIONS: "/transactions",
  CONTACT_US: "/contact-us",
  CONTACT_US_SUPPORT: "/contact-us/support",
  SETTINGS: "/settings",

  MEMBERS: "/members",
  MEMBERS_CELL_GROUPS: "/members/cell-groups",
  ALL_MEMBERS: "/all-members",
  MEMBER_DETAILS: "/all-members/:id",
  MEMBERSHIP_CLASS: "/subscriptions",

  COURSES_DETAILS: "/courses/:id",
  INSTRUCTORS: "/instructors",
  PROFILE: "/profile:id",
  PROFILE_SETTINGS: "/profile:id/settings",
  CONTACT_US_FAQS: "/faqs",
};
